public enum EPlayerAction
{
    ACTIVATE_ABILITY_0,
    ACTIVATE_ABILITY_1,
    ACTIVATE_ABILITY_2,
    ACTIVATE_ABILITY_3,
    ACTIVATE_ABILITY_4,
    ACTIVATE_ABILITY_5,

    UP,
    DOWN,
    LEFT,
    RIGHT,
    HOLD_DIRECTION,
    HOLD_POSITION,

}